version: 2.1
resource_class: macos.m1.medium.gen1
jobs:
  build:
    steps:
      - checkout
      - run: ./build.sh -mmac-arm64 -n bdist
      - store_artifacts:
          path:
            *.tar.gz

workflows:
  version: 2
  build:
    jobs:
      - build
