version: 2.1
resource_class: macos.m1.medium.gen1
jobs:
  build:
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run: brew install meson ninja gawk
      - run: ./build.sh -mmac-arm64 -n -p "main-<< pipeline.git.revision >>" bdist
      - store_artifacts:
          path: openslide-mac-arm64-main-<< pipeline.git.revision >>.tar.gz

workflows:
  version: 2
  build:
    jobs:
      - build
