version: 2.1
resource_class: macos.m1.medium.gen1
jobs:
  build:
    docker:
      - image: ghcr.io/alanocallaghan/winbuild-builder:latest
    steps:
      - checkout
      - run: ./build.sh -mmac-arm64 -n bdist

workflows:
  version: 2.1
  build:
    jobs:
      - build
