version: 2.1
resource_class: macos.m1.medium.gen1
jobs:
  build:
    macos:
    steps:
      - checkout
      - run:
          name: Build binary distribution
          command: |
            ./build.sh -mmac-arm64 -n -p "local" bdist

      - store_artifacts:
          path: openslide-mac-arm64-local.tar.gz

workflows:
  version: 2
  build:
    jobs:
      - build
