# Privileged workflow to process issue events

name: Issue event

on:
  issues:
    types: [opened]

permissions:
  issues: write

env:
  GH_LABEL: update

jobs:
  issue-event:
    name: Process
    runs-on: ubuntu-latest
    steps:
      - name: Get bot username
        id: bot-user
        env:
          GITHUB_TOKEN: ${{ secrets.OPENSLIDE_BOT_TOKEN }}
        run: echo "username=$(gh api user -q .login)" >> $GITHUB_OUTPUT
      - name: Label dependency issue
        if: >-
          github.actor == steps.bot-user.outputs.username &&
          contains(github.event.issue.body, 'topic=dependencies')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit -R "${{ github.repository }}" \
              "${{ github.event.issue.number }}" \
              --add-label $GH_LABEL
