# Build stable releases on push to openslide-winbuild main.
# Nightly builds from Git are handled elsewhere.

name: Build main

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    outputs:
      pkgver: ${{ steps.params.outputs.pkgver }}
    steps:
      - name: Calculate parameters
        id: params
        run: echo "pkgver=main-$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_OUTPUT

  stable:
    name: Stable
    needs: setup
    uses: ./.github/workflows/windows.yml
    with:
      openslide_winbuild_repo: ${{ github.repository }}
      openslide_winbuild_ref: ${{ github.ref }}
      pkgver: ${{ needs.setup.outputs.pkgver }}
