# Reusable workflow for building on Windows

name: Windows

on:
  workflow_call:
    inputs:
      openslide_repo:
        description: Override OpenSlide with this repo
        required: false
        type: string
      openslide_ref:
        description: Override OpenSlide with this openslide_repo ref
        required: false
        type: string
      openslide_java_repo:
        description: Override OpenSlide Java with this repo
        required: false
        type: string
      openslide_java_ref:
        description: Override OpenSlide Java with this openslide_java_repo ref
        required: false
        type: string
      openslide_winbuild_repo:
        description: Use openslide-winbuild from this repo
        required: false
        type: string
        default: openslide/openslide-winbuild
      openslide_winbuild_ref:
        description: Use openslide-winbuild from this ref
        required: false
        type: string
        default: main
      pkgver:
        description: Set package version string
        required: true
        type: string
    outputs:
      artifact:
        description: The name of the output artifact
        value: ${{ jobs.sdist.outputs.artifact }}

permissions:
  contents: read

jobs:
  sdist:
    name: Build source zip
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:36
    outputs:
      artifact: ${{ steps.prep.outputs.artifact }}
    steps:
      - name: Install dependencies
        run: |
          dnf install -y git-core mingw32-gcc wget xz zip
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.openslide_winbuild_repo }}
          ref: ${{ inputs.openslide_winbuild_ref }}

      - name: Install build dependencies
        if: inputs.openslide_repo != ''
        run: |
          dnf install -y gcc make autoconf automake libtool pkg-config \
              zlib-devel \
              libpng-devel \
              libjpeg-turbo-devel \
              libtiff-devel \
              openjpeg2-devel \
              gdk-pixbuf2-devel \
              libxml2-devel \
              sqlite-devel \
              cairo-devel \
              glib2-devel \
              doxygen
      - name: Check out OpenSlide
        if: inputs.openslide_repo != ''
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.openslide_repo }}
          ref: ${{ inputs.openslide_ref }}
          path: override/openslide
          persist-credentials: false
      - name: Check out OpenSlide Java
        if: inputs.openslide_java_repo != ''
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.openslide_java_repo }}
          ref: ${{ inputs.openslide_java_ref }}
          path: override/openslidejava
          persist-credentials: false
      - name: Autoreconf OpenSlide
        if: inputs.openslide_repo != ''
        working-directory: override/openslide
        run: |
          autoreconf -i
          # Generate openslide-tables.c
          ./configure
          make -j4
          make distclean
      - name: Autoreconf OpenSlide Java
        if: inputs.openslide_java_repo != ''
        working-directory: override/openslidejava
        run: autoreconf -i
      - name: Collect overrides
        if: inputs.openslide_repo != '' || inputs.openslide_java_repo != ''
        run: tar cf overrides.tar override
      - name: Upload overrides
        if: inputs.openslide_repo != '' || inputs.openslide_java_repo != ''
        # https://github.com/actions/upload-artifact/issues/233#issuecomment-991419457
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-overrides
          path: overrides.tar

      - name: Cache sources
        uses: actions/cache@v3
        with:
          key: winbuild-tar
          path: tar
      - name: Build source zip
        run: ./build.sh -p "${{ inputs.pkgver }}" sdist
      - name: Prep artifact
        id: prep
        run: |
          artifact="openslide-windows-${{ inputs.pkgver }}"
          echo "::set-output name=artifact::$artifact"
          mkdir -p "artifacts/$artifact"
          mv "openslide-winbuild-${{ inputs.pkgver }}.zip" "artifacts/$artifact"
      - name: Upload artifact
        # https://github.com/actions/upload-artifact/issues/233#issuecomment-991419457
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ steps.prep.outputs.artifact }}
          path: artifacts

  bdist:
    name: Build
    needs: sdist
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:36
    strategy:
      matrix:
        bits: [32, 64]
    steps:
      - name: Install dependencies
        run: |
          dnf install -y ant cmake gcc gettext git-core glib2-devel java \
              meson mingw${{ matrix.bits }}-gcc-c++ nasm wget xz zip
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.openslide_winbuild_repo }}
          ref: ${{ inputs.openslide_winbuild_ref }}
      - name: Download overrides
        if: inputs.openslide_repo != '' || inputs.openslide_java_repo != ''
        uses: actions/download-artifact@v3
        with:
          name: build-overrides
      - name: Unpack overrides
        if: inputs.openslide_repo != '' || inputs.openslide_java_repo != ''
        run: tar xf overrides.tar
      - name: Cache sources
        uses: actions/cache@v3
        with:
          key: winbuild-tar
          path: tar
      - name: Build binary zip
        run: |
          ./build.sh -j4 -m${{ matrix.bits }} -p "${{ inputs.pkgver }}" bdist
          mkdir -p "artifacts/${{ needs.sdist.outputs.artifact }}"
          mv "openslide-win${{ matrix.bits }}-${{ inputs.pkgver }}.zip" \
              "artifacts/${{ needs.sdist.outputs.artifact }}"
      - name: Upload artifact
        # https://github.com/actions/upload-artifact/issues/233#issuecomment-991419457
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ needs.sdist.outputs.artifact }}
          path: artifacts
